#!/usr/bin/env python3
import subprocess
from subprocess import check_output
import sys
import os

def getPlaneMode():

    output = check_output(["rfkill", "list", "all"], stderr=subprocess.STDOUT).decode("utf-8")
    rfkill_list = output.split("\n")
    plane_mode = True
    counter = 0
    
    for s in rfkill_list:
        if s[+1:-3] == "Soft blocked:" and not s[-3:] == "yes":
            plane_mode = False

    return plane_mode

if getPlaneMode(): 
    print(" enabled")
    if len(sys.argv) > 1:
        if sys.argv[1] == "change":
            os.system("rfkill unblock all")

else: 
    print("%{F#888} disabled%{F-}")
    if len(sys.argv) > 1:
        if sys.argv[1] == "change":
            os.system("rfkill block all")
