#!/usr/bin/env python3

from subprocess import check_output
import os
import re
import time as t

while True:

    config = dict(os.environ)
    status = check_output(['acpi'], universal_newlines=True)

    if not status:
        # stands for no battery found
        color = config.get("color_10", "red")
        fulltext = "<span color='{}'><span font='FontAwesome'>\uf00d \uf240</span></span>".format(color)
        percentleft = 100
    else:
        # if there is more than one battery in one laptop, the percentage left is
        # available for each battery separately, although state and remaining
        # time for overall block is shown in the status of the first battery
        batteries = status.split("\n")
        state_batteries=[]
        commasplitstatus_batteries=[]
        percentleft_batteries=[]
        time = ""
        for battery in batteries:
            if battery!='':
                state_batteries.append(battery.split(": ")[1].split(", ")[0])
                commasplitstatus = battery.split(", ")
                if not time:
                    time = commasplitstatus[-1].strip()
                    # check if it matches a time
                    time = re.match(r"(\d+):(\d+)", time)
                    if time:
                        time = ":".join(time.groups())
                        timeleft = " ({})".format(time)
                    else:
                        timeleft = ""

                p = int(commasplitstatus[1].rstrip("%\n"))
                if p>0:
                    percentleft_batteries.append(p)
                commasplitstatus_batteries.append(commasplitstatus)
        state = state_batteries[0]
        commasplitstatus = commasplitstatus_batteries[0]
        if percentleft_batteries:
            percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))
        else:
            percentleft = 0

    if state == "Discharging":
        if percentleft <= 20:
            if percentleft >= 10:
                os.system(f"notify-send -u critical \"Warning low battery: {percentleft}%\"")
            else:
                os.system(f"notify-send -u critical \"Warning low battery, the system will be suspended: {percentleft}%\"")
        
        if percentleft <= 7:
            os.system("systectl suspend")
    t.sleep(180)

